#include "lib_m.h"

int startOfLibMCalls(int curPC, int libMStartAddr){
	switch(curPC - libMStartAddr){
		case COSHF_OFFSET_M:
		case CBRTF_OFFSET_M:
		case NEARBYINT_OFFSET_M:
		case DREMF_OFFSET_M:
		case EXPM1F_OFFSET_M:
		case FINITEF_OFFSET_M:
		case ACOSH_OFFSET_M:
		case Y1_OFFSET_M:
		case Y0_OFFSET_M:
		case LOGBF_OFFSET_M:
		case FABSF_OFFSET_M:
		case LRINTF_OFFSET_M:
		case ILOGB_OFFSET_M:
		case FREXP_OFFSET_M:
		case ROUNDF_OFFSET_M:
		case CBRT_OFFSET_M:
		case MODFF_OFFSET_M:
		case SCALBF_OFFSET_M:
		case LGAMMAF_OFFSET_M:
		case SCALBNF_OFFSET_M:
		case YN_OFFSET_M:
		case TGAMMA_OFFSET_M:
		case SCALBN_OFFSET_M:
		case CEIL_OFFSET_M:
		case FMAF_OFFSET_M:
		case YNF_OFFSET_M:
		case SCALBLNF_OFFSET_M:
		case RINT_OFFSET_M:
		case FMOD_OFFSET_M:
		case ROUND_OFFSET_M:
		case JNF_OFFSET_M:
		case COSF_OFFSET_M:
		case NEXTAFTERF_OFFSET_M:
		case REMQUOF_OFFSET_M:
		case J0_OFFSET_M:
		case J1_OFFSET_M:
		case COSH_OFFSET_M:
		case LOGF_OFFSET_M:
		case FMINL_OFFSET_M:
		case HYPOT_OFFSET_M:
		case LOGB_OFFSET_M:
		case SINHF_OFFSET_M:
		case ACOSF_OFFSET_M:
		case SINCOS_OFFSET_M:
		case ASIN_OFFSET_M:
		case ISNAN_OFFSET_M:
		case SCALB_OFFSET_M:
		case NANL_OFFSET_M:
		case Y1F_OFFSET_M:
		case NANF_OFFSET_M:
		case ERFCF_OFFSET_M:
		case LLROUNDL_OFFSET_M:
		case LDEXPF_OFFSET_M:
		case ATAN2F_OFFSET_M:
		case LLROUNDF_OFFSET_M:
		case MODF_OFFSET_M:
		case FMAX_OFFSET_M:
		case TGAMMAF_OFFSET_M:
		case LOG1PF_OFFSET_M:
		case COPYSIGN_OFFSET_M:
		case SIGNIFICANDF_OFFSET_M:
		case ILOGBL_OFFSET_M:
		case JN_OFFSET_M:
		case DREM_OFFSET_M:
		case TRUNCF_OFFSET_M:
		case ACOSHF_OFFSET_M:
		case SINF_OFFSET_M:
		case ILOGBF_OFFSET_M:
		case REMAINDER_OFFSET_M:
		case TRUNC_OFFSET_M:
		case EXPM1_OFFSET_M:
		case LROUNDF_OFFSET_M:
		case ATANHF_OFFSET_M:
		case LROUNDL_OFFSET_M:
		case ERFF_OFFSET_M:
		case SIGNGAM_OFFSET_M:
		case ERFC_OFFSET_M:
		case FMIN_OFFSET_M:
		case LLROUND_OFFSET_M:
		case ACOS_OFFSET_M:
		case GAMMA_OFFSET_M:
		case ROUNDL_OFFSET_M:
		case SINH_OFFSET_M:
		case FLOORF_OFFSET_M:
		case FMAXF_OFFSET_M:
		case J1F_OFFSET_M:
		case POW_OFFSET_M:
		case FLOORL_OFFSET_M:
		case FMAXL_OFFSET_M:
		case FABSL_OFFSET_M:
		case LDEXP_OFFSET_M:
		case SQRTF_OFFSET_M:
		case HYPOTF_OFFSET_M:
		case COPYSIGNF_OFFSET_M:
		case LOG_OFFSET_M:
		case FDIMF_OFFSET_M:
		case EXP2_OFFSET_M:
		case LROUND_OFFSET_M:
		case FMINF_OFFSET_M:
		case LOG10_OFFSET_M:
		case TANHF_OFFSET_M:
		case GAMMA_R_OFFSET_M:
		case ASINH_OFFSET_M:
		case NEXTTOWARDF_OFFSET_M:
		case NEARBYINTF_OFFSET_M:
		case ASINF_OFFSET_M:
		case COS_OFFSET_M:
		case J0F_OFFSET_M:
		case LLRINT_OFFSET_M:
		case LRINT_OFFSET_M:
		case LLRINTF_OFFSET_M:
		case TRUNCL_OFFSET_M:
		case TANH_OFFSET_M:
		case FDIM_OFFSET_M:
		case TANF_OFFSET_M:
		case SCALBLNL_OFFSET_M:
		case RINTF_OFFSET_M:
		case LGAMMA_OFFSET_M:
		case ERF_OFFSET_M:
		case Y0F_OFFSET_M:
		case LGAMMAF_R_OFFSET_M:
		case FMA_OFFSET_M:
		case LOG1P_OFFSET_M:
		case EXPF_OFFSET_M:
		case LOG10F_OFFSET_M:
		case LGAMMA_R_OFFSET_M:
		case TAN_OFFSET_M:
		case ATANF_OFFSET_M:
		case FABS_OFFSET_M:
		case FLOOR_OFFSET_M:
		case ATANH_OFFSET_M:
		case COPYSIGNL_OFFSET_M:
		case SQRT_OFFSET_M:
		case GAMMAF_R_OFFSET_M:
		case FMODF_OFFSET_M:
		case FINITE_OFFSET_M:
		case SIN_OFFSET_M:
		case NEXTAFTER_OFFSET_M:
		case FREXPF_OFFSET_M:
		case CEILF_OFFSET_M:
		case ATAN_OFFSET_M:
		case CEILL_OFFSET_M:
		case GAMMAF_OFFSET_M:
		case REMAINDERF_OFFSET_M:
		case ISNANF_OFFSET_M:
		case SIGNIFICAND_OFFSET_M:
		case EXP2F_OFFSET_M:
		case POWF_OFFSET_M:
		case ATAN2_OFFSET_M:
		case ASINHF_OFFSET_M:
		case EXP_OFFSET_M:
		case REMQUO_OFFSET_M:
		case SINCOSF_OFFSET_M:
			return (1);
		default:
			return (0);
	}
	return (0);
}

sysLibHookHandler hookLibMCalls(int curPC, int libMStartAddr, CPUState* env){
	switch(curPC - libMStartAddr){
		/*
		case COSHF_OFFSET_M:
			sysLibMCoshfHookHandler(env, 1);
			return sysLibMCoshfHookHandler;
		case CBRTF_OFFSET_M:
			sysLibMCbrtfHookHandler(env, 1);
			return sysLibMCbrtfHookHandler;
		case NEARBYINT_OFFSET_M:
			sysLibMNearbyintHookHandler(env, 1);
			return sysLibMNearbyintHookHandler;
		case DREMF_OFFSET_M:
			sysLibMDremfHookHandler(env, 1);
			return sysLibMDremfHookHandler;
		case EXPM1F_OFFSET_M:
			sysLibMExpm1FHookHandler(env, 1);
			return sysLibMExpm1FHookHandler;
		case FINITEF_OFFSET_M:
			sysLibMFinitefHookHandler(env, 1);
			return sysLibMFinitefHookHandler;
		case ACOSH_OFFSET_M:
			sysLibMAcoshHookHandler(env, 1);
			return sysLibMAcoshHookHandler;
		case Y1_OFFSET_M:
			sysLibMY1HookHandler(env, 1);
			return sysLibMY1HookHandler;
		case Y0_OFFSET_M:
			sysLibMY0HookHandler(env, 1);
			return sysLibMY0HookHandler;
		case LOGBF_OFFSET_M:
			sysLibMLogbfHookHandler(env, 1);
			return sysLibMLogbfHookHandler;
		case FABSF_OFFSET_M:
			sysLibMFabsfHookHandler(env, 1);
			return sysLibMFabsfHookHandler;
		case LRINTF_OFFSET_M:
			sysLibMLrintfHookHandler(env, 1);
			return sysLibMLrintfHookHandler;
		case ILOGB_OFFSET_M:
			sysLibMIlogbHookHandler(env, 1);
			return sysLibMIlogbHookHandler;
		case FREXP_OFFSET_M:
			sysLibMFrexpHookHandler(env, 1);
			return sysLibMFrexpHookHandler;
		case ROUNDF_OFFSET_M:
			sysLibMRoundfHookHandler(env, 1);
			return sysLibMRoundfHookHandler;
		case CBRT_OFFSET_M:
			sysLibMCbrtHookHandler(env, 1);
			return sysLibMCbrtHookHandler;
		case MODFF_OFFSET_M:
			sysLibMModffHookHandler(env, 1);
			return sysLibMModffHookHandler;
		case SCALBF_OFFSET_M:
			sysLibMScalbfHookHandler(env, 1);
			return sysLibMScalbfHookHandler;
		case LGAMMAF_OFFSET_M:
			sysLibMLgammafHookHandler(env, 1);
			return sysLibMLgammafHookHandler;
		case SCALBNF_OFFSET_M:
			sysLibMScalbnfHookHandler(env, 1);
			return sysLibMScalbnfHookHandler;
		case YN_OFFSET_M:
			sysLibMYnHookHandler(env, 1);
			return sysLibMYnHookHandler;
		case TGAMMA_OFFSET_M:
			sysLibMTgammaHookHandler(env, 1);
			return sysLibMTgammaHookHandler;
		case SCALBN_OFFSET_M:
			sysLibMScalbnHookHandler(env, 1);
			return sysLibMScalbnHookHandler;
		case CEIL_OFFSET_M:
			sysLibMCeilHookHandler(env, 1);
			return sysLibMCeilHookHandler;
		case FMAF_OFFSET_M:
			sysLibMFmafHookHandler(env, 1);
			return sysLibMFmafHookHandler;
		case YNF_OFFSET_M:
			sysLibMYnfHookHandler(env, 1);
			return sysLibMYnfHookHandler;
		case SCALBLNF_OFFSET_M:
			sysLibMScalblnfHookHandler(env, 1);
			return sysLibMScalblnfHookHandler;
		case RINT_OFFSET_M:
			sysLibMRintHookHandler(env, 1);
			return sysLibMRintHookHandler;
		case FMOD_OFFSET_M:
			sysLibMFmodHookHandler(env, 1);
			return sysLibMFmodHookHandler;
		case ROUND_OFFSET_M:
			sysLibMRoundHookHandler(env, 1);
			return sysLibMRoundHookHandler;
		case JNF_OFFSET_M:
			sysLibMJnfHookHandler(env, 1);
			return sysLibMJnfHookHandler;
		case COSF_OFFSET_M:
			sysLibMCosfHookHandler(env, 1);
			return sysLibMCosfHookHandler;
		case NEXTAFTERF_OFFSET_M:
			sysLibMNextafterfHookHandler(env, 1);
			return sysLibMNextafterfHookHandler;
		case REMQUOF_OFFSET_M:
			sysLibMRemquofHookHandler(env, 1);
			return sysLibMRemquofHookHandler;
		case J0_OFFSET_M:
			sysLibMJ0HookHandler(env, 1);
			return sysLibMJ0HookHandler;
		case J1_OFFSET_M:
			sysLibMJ1HookHandler(env, 1);
			return sysLibMJ1HookHandler;
		case COSH_OFFSET_M:
			sysLibMCoshHookHandler(env, 1);
			return sysLibMCoshHookHandler;
		case LOGF_OFFSET_M:
			sysLibMLogfHookHandler(env, 1);
			return sysLibMLogfHookHandler;
		case FMINL_OFFSET_M:
			sysLibMFminlHookHandler(env, 1);
			return sysLibMFminlHookHandler;
		case HYPOT_OFFSET_M:
			sysLibMHypotHookHandler(env, 1);
			return sysLibMHypotHookHandler;
		case LOGB_OFFSET_M:
			sysLibMLogbHookHandler(env, 1);
			return sysLibMLogbHookHandler;
		case SINHF_OFFSET_M:
			sysLibMSinhfHookHandler(env, 1);
			return sysLibMSinhfHookHandler;
		case ACOSF_OFFSET_M:
			sysLibMAcosfHookHandler(env, 1);
			return sysLibMAcosfHookHandler;
		case SINCOS_OFFSET_M:
			sysLibMSincosHookHandler(env, 1);
			return sysLibMSincosHookHandler;
		case ASIN_OFFSET_M:
			sysLibMAsinHookHandler(env, 1);
			return sysLibMAsinHookHandler;
		case ISNAN_OFFSET_M:
			sysLibMIsnanHookHandler(env, 1);
			return sysLibMIsnanHookHandler;
		case SCALB_OFFSET_M:
			sysLibMScalbHookHandler(env, 1);
			return sysLibMScalbHookHandler;
		case NANL_OFFSET_M:
			sysLibMNanlHookHandler(env, 1);
			return sysLibMNanlHookHandler;
		case Y1F_OFFSET_M:
			sysLibMY1FHookHandler(env, 1);
			return sysLibMY1FHookHandler;
		case NANF_OFFSET_M:
			sysLibMNanfHookHandler(env, 1);
			return sysLibMNanfHookHandler;
		case ERFCF_OFFSET_M:
			sysLibMErfcfHookHandler(env, 1);
			return sysLibMErfcfHookHandler;
		case LLROUNDL_OFFSET_M:
			sysLibMLlroundlHookHandler(env, 1);
			return sysLibMLlroundlHookHandler;
		case LDEXPF_OFFSET_M:
			sysLibMLdexpfHookHandler(env, 1);
			return sysLibMLdexpfHookHandler;
		case ATAN2F_OFFSET_M:
			sysLibMAtan2FHookHandler(env, 1);
			return sysLibMAtan2FHookHandler;
		case LLROUNDF_OFFSET_M:
			sysLibMLlroundfHookHandler(env, 1);
			return sysLibMLlroundfHookHandler;
		case MODF_OFFSET_M:
			sysLibMModfHookHandler(env, 1);
			return sysLibMModfHookHandler;
		case FMAX_OFFSET_M:
			sysLibMFmaxHookHandler(env, 1);
			return sysLibMFmaxHookHandler;
		case TGAMMAF_OFFSET_M:
			sysLibMTgammafHookHandler(env, 1);
			return sysLibMTgammafHookHandler;
		case LOG1PF_OFFSET_M:
			sysLibMLog1PfHookHandler(env, 1);
			return sysLibMLog1PfHookHandler;
		case COPYSIGN_OFFSET_M:
			sysLibMCopysignHookHandler(env, 1);
			return sysLibMCopysignHookHandler;
		case SIGNIFICANDF_OFFSET_M:
			sysLibMSignificandfHookHandler(env, 1);
			return sysLibMSignificandfHookHandler;
		case ILOGBL_OFFSET_M:
			sysLibMIlogblHookHandler(env, 1);
			return sysLibMIlogblHookHandler;
		case JN_OFFSET_M:
			sysLibMJnHookHandler(env, 1);
			return sysLibMJnHookHandler;
		case DREM_OFFSET_M:
			sysLibMDremHookHandler(env, 1);
			return sysLibMDremHookHandler;
		case TRUNCF_OFFSET_M:
			sysLibMTruncfHookHandler(env, 1);
			return sysLibMTruncfHookHandler;
		case ACOSHF_OFFSET_M:
			sysLibMAcoshfHookHandler(env, 1);
			return sysLibMAcoshfHookHandler;
		case SINF_OFFSET_M:
			sysLibMSinfHookHandler(env, 1);
			return sysLibMSinfHookHandler;
		case ILOGBF_OFFSET_M:
			sysLibMIlogbfHookHandler(env, 1);
			return sysLibMIlogbfHookHandler;
		case REMAINDER_OFFSET_M:
			sysLibMRemainderHookHandler(env, 1);
			return sysLibMRemainderHookHandler;
		case TRUNC_OFFSET_M:
			sysLibMTruncHookHandler(env, 1);
			return sysLibMTruncHookHandler;
		case EXPM1_OFFSET_M:
			sysLibMExpm1HookHandler(env, 1);
			return sysLibMExpm1HookHandler;
		case LROUNDF_OFFSET_M:
			sysLibMLroundfHookHandler(env, 1);
			return sysLibMLroundfHookHandler;
		case ATANHF_OFFSET_M:
			sysLibMAtanhfHookHandler(env, 1);
			return sysLibMAtanhfHookHandler;
		case LROUNDL_OFFSET_M:
			sysLibMLroundlHookHandler(env, 1);
			return sysLibMLroundlHookHandler;
		case ERFF_OFFSET_M:
			sysLibMErffHookHandler(env, 1);
			return sysLibMErffHookHandler;
		case SIGNGAM_OFFSET_M:
			sysLibMSigngamHookHandler(env, 1);
			return sysLibMSigngamHookHandler;
		case ERFC_OFFSET_M:
			sysLibMErfcHookHandler(env, 1);
			return sysLibMErfcHookHandler;
		case FMIN_OFFSET_M:
			sysLibMFminHookHandler(env, 1);
			return sysLibMFminHookHandler;
		case LLROUND_OFFSET_M:
			sysLibMLlroundHookHandler(env, 1);
			return sysLibMLlroundHookHandler;
		case ACOS_OFFSET_M:
			sysLibMAcosHookHandler(env, 1);
			return sysLibMAcosHookHandler;
		case GAMMA_OFFSET_M:
			sysLibMGammaHookHandler(env, 1);
			return sysLibMGammaHookHandler;
		case ROUNDL_OFFSET_M:
			sysLibMRoundlHookHandler(env, 1);
			return sysLibMRoundlHookHandler;
		case SINH_OFFSET_M:
			sysLibMSinhHookHandler(env, 1);
			return sysLibMSinhHookHandler;
		case FLOORF_OFFSET_M:
			sysLibMFloorfHookHandler(env, 1);
			return sysLibMFloorfHookHandler;
		case FMAXF_OFFSET_M:
			sysLibMFmaxfHookHandler(env, 1);
			return sysLibMFmaxfHookHandler;
		case J1F_OFFSET_M:
			sysLibMJ1FHookHandler(env, 1);
			return sysLibMJ1FHookHandler;
		case POW_OFFSET_M:
			sysLibMPowHookHandler(env, 1);
			return sysLibMPowHookHandler;
		case FLOORL_OFFSET_M:
			sysLibMFloorlHookHandler(env, 1);
			return sysLibMFloorlHookHandler;
		case FMAXL_OFFSET_M:
			sysLibMFmaxlHookHandler(env, 1);
			return sysLibMFmaxlHookHandler;
		case FABSL_OFFSET_M:
			sysLibMFabslHookHandler(env, 1);
			return sysLibMFabslHookHandler;
		case LDEXP_OFFSET_M:
			sysLibMLdexpHookHandler(env, 1);
			return sysLibMLdexpHookHandler;
		case SQRTF_OFFSET_M:
			sysLibMSqrtfHookHandler(env, 1);
			return sysLibMSqrtfHookHandler;
		case HYPOTF_OFFSET_M:
			sysLibMHypotfHookHandler(env, 1);
			return sysLibMHypotfHookHandler;
		case COPYSIGNF_OFFSET_M:
			sysLibMCopysignfHookHandler(env, 1);
			return sysLibMCopysignfHookHandler;
		case LOG_OFFSET_M:
			sysLibMLogHookHandler(env, 1);
			return sysLibMLogHookHandler;
		case FDIMF_OFFSET_M:
			sysLibMFdimfHookHandler(env, 1);
			return sysLibMFdimfHookHandler;
		case EXP2_OFFSET_M:
			sysLibMExp2HookHandler(env, 1);
			return sysLibMExp2HookHandler;
		case LROUND_OFFSET_M:
			sysLibMLroundHookHandler(env, 1);
			return sysLibMLroundHookHandler;
		case FMINF_OFFSET_M:
			sysLibMFminfHookHandler(env, 1);
			return sysLibMFminfHookHandler;
		case LOG10_OFFSET_M:
			sysLibMLog10HookHandler(env, 1);
			return sysLibMLog10HookHandler;
		case TANHF_OFFSET_M:
			sysLibMTanhfHookHandler(env, 1);
			return sysLibMTanhfHookHandler;
		case GAMMA_R_OFFSET_M:
			sysLibMGamma_RHookHandler(env, 1);
			return sysLibMGamma_RHookHandler;
		case ASINH_OFFSET_M:
			sysLibMAsinhHookHandler(env, 1);
			return sysLibMAsinhHookHandler;
		case NEXTTOWARDF_OFFSET_M:
			sysLibMNexttowardfHookHandler(env, 1);
			return sysLibMNexttowardfHookHandler;
		case NEARBYINTF_OFFSET_M:
			sysLibMNearbyintfHookHandler(env, 1);
			return sysLibMNearbyintfHookHandler;
		case ASINF_OFFSET_M:
			sysLibMAsinfHookHandler(env, 1);
			return sysLibMAsinfHookHandler;
		case COS_OFFSET_M:
			sysLibMCosHookHandler(env, 1);
			return sysLibMCosHookHandler;
		case J0F_OFFSET_M:
			sysLibMJ0FHookHandler(env, 1);
			return sysLibMJ0FHookHandler;
		case LLRINT_OFFSET_M:
			sysLibMLlrintHookHandler(env, 1);
			return sysLibMLlrintHookHandler;
		case LRINT_OFFSET_M:
			sysLibMLrintHookHandler(env, 1);
			return sysLibMLrintHookHandler;
		case LLRINTF_OFFSET_M:
			sysLibMLlrintfHookHandler(env, 1);
			return sysLibMLlrintfHookHandler;
		case TRUNCL_OFFSET_M:
			sysLibMTrunclHookHandler(env, 1);
			return sysLibMTrunclHookHandler;
		case TANH_OFFSET_M:
			sysLibMTanhHookHandler(env, 1);
			return sysLibMTanhHookHandler;
		case FDIM_OFFSET_M:
			sysLibMFdimHookHandler(env, 1);
			return sysLibMFdimHookHandler;
		case TANF_OFFSET_M:
			sysLibMTanfHookHandler(env, 1);
			return sysLibMTanfHookHandler;
		case SCALBLNL_OFFSET_M:
			sysLibMScalblnlHookHandler(env, 1);
			return sysLibMScalblnlHookHandler;
		case RINTF_OFFSET_M:
			sysLibMRintfHookHandler(env, 1);
			return sysLibMRintfHookHandler;
		case LGAMMA_OFFSET_M:
			sysLibMLgammaHookHandler(env, 1);
			return sysLibMLgammaHookHandler;
		case ERF_OFFSET_M:
			sysLibMErfHookHandler(env, 1);
			return sysLibMErfHookHandler;
		case Y0F_OFFSET_M:
			sysLibMY0FHookHandler(env, 1);
			return sysLibMY0FHookHandler;
		case LGAMMAF_R_OFFSET_M:
			sysLibMLgammaf_RHookHandler(env, 1);
			return sysLibMLgammaf_RHookHandler;
		case FMA_OFFSET_M:
			sysLibMFmaHookHandler(env, 1);
			return sysLibMFmaHookHandler;
		case LOG1P_OFFSET_M:
			sysLibMLog1PHookHandler(env, 1);
			return sysLibMLog1PHookHandler;
		case EXPF_OFFSET_M:
			sysLibMExpfHookHandler(env, 1);
			return sysLibMExpfHookHandler;
		case LOG10F_OFFSET_M:
			sysLibMLog10FHookHandler(env, 1);
			return sysLibMLog10FHookHandler;
		case LGAMMA_R_OFFSET_M:
			sysLibMLgamma_RHookHandler(env, 1);
			return sysLibMLgamma_RHookHandler;
		case TAN_OFFSET_M:
			sysLibMTanHookHandler(env, 1);
			return sysLibMTanHookHandler;
		case ATANF_OFFSET_M:
			sysLibMAtanfHookHandler(env, 1);
			return sysLibMAtanfHookHandler;
		case FABS_OFFSET_M:
			sysLibMFabsHookHandler(env, 1);
			return sysLibMFabsHookHandler;
		case FLOOR_OFFSET_M:
			sysLibMFloorHookHandler(env, 1);
			return sysLibMFloorHookHandler;
		case ATANH_OFFSET_M:
			sysLibMAtanhHookHandler(env, 1);
			return sysLibMAtanhHookHandler;
		case COPYSIGNL_OFFSET_M:
			sysLibMCopysignlHookHandler(env, 1);
			return sysLibMCopysignlHookHandler;
		case SQRT_OFFSET_M:
			sysLibMSqrtHookHandler(env, 1);
			return sysLibMSqrtHookHandler;
		case GAMMAF_R_OFFSET_M:
			sysLibMGammaf_RHookHandler(env, 1);
			return sysLibMGammaf_RHookHandler;
		case FMODF_OFFSET_M:
			sysLibMFmodfHookHandler(env, 1);
			return sysLibMFmodfHookHandler;
		case FINITE_OFFSET_M:
			sysLibMFiniteHookHandler(env, 1);
			return sysLibMFiniteHookHandler;
		case SIN_OFFSET_M:
			sysLibMSinHookHandler(env, 1);
			return sysLibMSinHookHandler;
		case NEXTAFTER_OFFSET_M:
			sysLibMNextafterHookHandler(env, 1);
			return sysLibMNextafterHookHandler;
		case FREXPF_OFFSET_M:
			sysLibMFrexpfHookHandler(env, 1);
			return sysLibMFrexpfHookHandler;
		case CEILF_OFFSET_M:
			sysLibMCeilfHookHandler(env, 1);
			return sysLibMCeilfHookHandler;
		case ATAN_OFFSET_M:
			sysLibMAtanHookHandler(env, 1);
			return sysLibMAtanHookHandler;
		case CEILL_OFFSET_M:
			sysLibMCeillHookHandler(env, 1);
			return sysLibMCeillHookHandler;
		case GAMMAF_OFFSET_M:
			sysLibMGammafHookHandler(env, 1);
			return sysLibMGammafHookHandler;
		case REMAINDERF_OFFSET_M:
			sysLibMRemainderfHookHandler(env, 1);
			return sysLibMRemainderfHookHandler;
		case ISNANF_OFFSET_M:
			sysLibMIsnanfHookHandler(env, 1);
			return sysLibMIsnanfHookHandler;
		case SIGNIFICAND_OFFSET_M:
			sysLibMSignificandHookHandler(env, 1);
			return sysLibMSignificandHookHandler;
		case EXP2F_OFFSET_M:
			sysLibMExp2FHookHandler(env, 1);
			return sysLibMExp2FHookHandler;
		case POWF_OFFSET_M:
			sysLibMPowfHookHandler(env, 1);
			return sysLibMPowfHookHandler;
		case ATAN2_OFFSET_M:
			sysLibMAtan2HookHandler(env, 1);
			return sysLibMAtan2HookHandler;
		case ASINHF_OFFSET_M:
			sysLibMAsinhfHookHandler(env, 1);
			return sysLibMAsinhfHookHandler;
		case EXP_OFFSET_M:
			sysLibMExpHookHandler(env, 1);
			return sysLibMExpHookHandler;
		case REMQUO_OFFSET_M:
			sysLibMRemquoHookHandler(env, 1);
			return sysLibMRemquoHookHandler;
		case SINCOSF_OFFSET_M:
			sysLibMSincosfHookHandler(env, 1);
			return sysLibMSincosfHookHandler;
			*/
		default:
			break;
	}
	return (NULL);
}
